### ISSUE TITLE
Does not work for latest spree

### ISSUE THREAD

**Issue by jodibooksHQ** [godaddy/spree_weight_based_shipping_calculator#4]
Hi, I've used the rails_50 branch and updated the spree gem.  I cannot add the calculator to my configuration, the `validate_at_least_one_rate` error throws because there are no rates. If I disable validation, only the field for `default_item_weight` shows up. 

Do you know a quick fix to make it possible to enter rates?

**Comment by jodibooksHQ** [comment]
Oh, nevermind. "Note: Currently, UI for Admin is not provided in this gem."

So, basically, using `rails_50` branch as basis and upgrading the dependencies seems to include it in spree.

**Comment by kesmith-godaddy** [comment]
Report has resolved issue.
